apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-services
  labels:
    app: micros
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micros
  template:
    metadata:
      labels:
        app: micros
    spec:
      containers:
        - name: api-gateway
          image: aleramiirez/generics:api-gateway
          ports:
            - containerPort: 8084
          env:
            - name: AUDIT_API
              value: http://nlb-service:8084
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: DATABASE_URL
              value: jdbc:mysql://generics-sql-server.mysql.database.azure.com:3306/generics_sql?useSSL=true
            - name: DATABASE_USERNAME
              value: aleramiirez
            - name: DATABASE_PASSWORD
              value: Password0
        - name: register-service
          image: aleramiirez/generics:register-service
          ports:
            - containerPort: 8081
          env:
            - name: AUDIT_API
              value: http://nlb-service:8081
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: DATABASE_URL
              value: jdbc:mysql://generics-sql-server.mysql.database.azure.com:3306/generics_sql?useSSL=true
            - name: DATABASE_USERNAME
              value: aleramiirez
            - name: DATABASE_PASSWORD
              value: Password0
        - name: crud-service
          image: aleramiirez/generics:crud-service
          ports:
            - containerPort: 8082
          env:
            - name: AUDIT_API
              value: http://nlb-service:8082
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: DATABASE_URL
              value: jdbc:mysql://generics-sql-server.mysql.database.azure.com:3306/generics_sql?useSSL=true
            - name: DATABASE_USERNAME
              value: aleramiirez
            - name: DATABASE_PASSWORD
              value: Password0
        - name: generics-front
          image: aleramiirez/generics:generics-front
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: jdbc:mysql://generics-sql-server.mysql.database.azure.com:3306/generics_sql?useSSL=true
            - name: DATABASE_USERNAME
              value: aleramiirez
            - name: DATABASE_PASSWORD
              value: Password0